// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_Ub48BlaPouXJYrbSVGe52X8fsfGjEo',
    appId: '1:895929952131:web:e1cc8988e75f1032d3f8b6',
    messagingSenderId: '895929952131',
    projectId: 'flutter-main-41a99',
    authDomain: 'flutter-main-41a99.firebaseapp.com',
    storageBucket: 'flutter-main-41a99.appspot.com',
    measurementId: 'G-W16XM0YT7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7PEEvG7BU6vgDOYYJhQ04yj_rigLHWA',
    appId: '1:895929952131:android:efe0aa60bf27aecdd3f8b6',
    messagingSenderId: '895929952131',
    projectId: 'flutter-main-41a99',
    storageBucket: 'flutter-main-41a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7nZei4o5d4Xrpo7JwzsR0GSWqjfrotpI',
    appId: '1:895929952131:ios:9d30b1825cf3a732d3f8b6',
    messagingSenderId: '895929952131',
    projectId: 'flutter-main-41a99',
    storageBucket: 'flutter-main-41a99.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7nZei4o5d4Xrpo7JwzsR0GSWqjfrotpI',
    appId: '1:895929952131:ios:f8ddfd99d716187ad3f8b6',
    messagingSenderId: '895929952131',
    projectId: 'flutter-main-41a99',
    storageBucket: 'flutter-main-41a99.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
