// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuPmB46HkPQgknsfCPHVVQRbzzfZZz-I',
    appId: '1:488740562725:web:a5cccb3855fac299139ccc',
    messagingSenderId: '488740562725',
    projectId: 'skin-cancer-59ce1',
    authDomain: 'skin-cancer-59ce1.firebaseapp.com',
    storageBucket: 'skin-cancer-59ce1.appspot.com',
    measurementId: 'G-GCD5LVTWK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1shLvt1zRDWakY4U2PhHZfemWBBQKL_I',
    appId: '1:488740562725:android:c18b0866eff2a723139ccc',
    messagingSenderId: '488740562725',
    projectId: 'skin-cancer-59ce1',
    storageBucket: 'skin-cancer-59ce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN3knBnVwILfKOGbB4Iw0ybOTvWhZAtno',
    appId: '1:488740562725:ios:aebf6dcd8fd66213139ccc',
    messagingSenderId: '488740562725',
    projectId: 'skin-cancer-59ce1',
    storageBucket: 'skin-cancer-59ce1.appspot.com',
    iosClientId: '488740562725-31bcbeq0keqcfec3v5c78iqj9gbrd71r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN3knBnVwILfKOGbB4Iw0ybOTvWhZAtno',
    appId: '1:488740562725:ios:4c30e4dbb228c8fa139ccc',
    messagingSenderId: '488740562725',
    projectId: 'skin-cancer-59ce1',
    storageBucket: 'skin-cancer-59ce1.appspot.com',
    iosClientId: '488740562725-ocm0bg31cn832qp2b6h0kdiedq654h70.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
